name: Clone External Repository and Use It

on:
  workflow_dispatch: # Pemicu manual (bisa diganti sesuai kebutuhan)

jobs:
  clone-and-use:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout current repository
        uses: actions/checkout@v3
      
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20.x'

      - name: Change working directory
        run: cd /home/runner/work/test-epg/test-epg

      - name: Clone external repository
        run: |
          echo "Cloning external repository..."
          git clone --depth 1 -b master https://github.com/iptv-org/epg.git external-repo

      - name: Install dependencies
        run: npm install
      
      - name: Run script
        run: npx tsx scripts/commands/epg/grab.ts --channels=chlist.txt
