name: Run Bash Script in Workflow

on:
  schedule:
    - cron: "0 2 * * *"

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      
      - name: Run Script Directly
        run: |
          echo "Changing to the epg directory..."
          cd epg || { echo "Failed to change directory to 'epg'. Exiting."; exit 1; }
          echo "Running npm grab command..."
          npm run grab -- --channels=chlist.txt
