name: clone repo

on:
  schedule:
    - cron: "50 13 28 03 *"

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      
      - name: Run Script Directly
        run: |
          echo "clone"
          git clone --depth 1 -b master https://github.com/iptv-org/epg.git
