name: Clone External Repository and Use It

on:
  workflow_dispatch: # Pemicu manual (bisa diganti sesuai kebutuhan)

jobs:
  clone-and-use:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout current repository
        uses: actions/checkout@v3
      
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20.x'

      - name: Change working directory
        run: |
          cd /home/runner/work/test-epg/test-epg
          npm init

      - name: Clone external repository
        run: |
          echo "Cloning external repository..."
          git clone --depth 1 -b master https://github.com/iptv-org/epg.git external-repo

      - name: Initialize Node.js in external repository
        run: |
          cd external-repo
          npm init -y

      - name: Install dependencies in external repository
        run: |
          cd external-repo
          npm install

      - name: Download chlist.txt file
        run: |
          cd external-repo
          curl -o chlist.txt https://raw.githubusercontent.com/kemalsyabaniadama/test-epg/refs/heads/main/.github/workflows/chlist.txt

      - name: Run script
        run: |
          cd external-repo
          npx tsx scripts/commands/epg/grab.ts --channels=chlist.txt

      - name: Copy EPG file to main repository
        run: |
          cp external-repo/guide.xml .

      - name: Commit and Push EPG file
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global user.email "action@github.com"
          git config --global user.name "GitHub Actions Bot"
          git add guide.xml
          git commit -m "Upload generated guide.xml"
          git push
